/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useTurnable } from '../hooks/useTurnable'

export default function Model(props) {
  const ref = useTurnable('z')
  const { nodes, materials } = useGLTF('/glb/keyhole.glb')

  return (
    <group ref={ref} {...props}>
      <mesh
        material={materials['04 - Default']}
        geometry={nodes.Spring001.geometry}
        position={[-0.09, 0.2, -0.87]}
        rotation={[0, 0, -0.26]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials['02 - Default']}
        geometry={nodes.Cylinder003.geometry}
        position={[-0.37, 0.3, 0.02]}
        rotation={[0, -0.26, 0.26]}
        scale={[0.03, 0.03, 0.03]}
      />
      <pointLight position={[10, 10, 10]} intensity={0.75} />
    </group>
  )
}

useGLTF.preload('/keyhole.glb')
